name: Build Landing
on: workflow_dispatch

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_BLOG_SLUG: blog 
          envkey_WEBSITE_LANGUAGE: en
          envkey_CURRENCY: EUR
          envkey_UNITS: metric
          envkey_NODE_VERSION: 20
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Build landing
        run: npm install && npm run build
